{
  "EndClientUserUniqueSessionId": "Uniquesession",
  "Policy": {
    "ProductNumber": "ISO Commercial Automobile",
    "ProductVerNumber": "ISO_CA_V1",
    "EventName": "ISO_CA_Rate_FormSelection",
    "ISOERCVersion": "RC_CA_CT_02012019_V01",
    "ISOCWVersion": "RC_CA_CW_11012016_V01",
    "EffectiveDate": "2019-02-01",
    "ExpirationDate": "2020-02-01",
    "LastRateLookUpDate": "2018-07-17",
    "InsuredName": "John Smith",
    "AddressLine1": "27TH ST",
    "AddressLine2": "PHOENIX",
    "City": "MILFORD",
    "County": "NEW HAVEN",
    "ZipCode": "06001",
    "State": "CT",
    "OptionalClassPlan": "No",
    "PolicyType": "Business Auto Coverage Form",
    "IndividualNamedInsuredOnThePolicy": "Yes",
    "CommercialAutoPublicTransportationAutos": "Yes",
    "CommercialAutoPublicOrLiveryPassengerConveyanceExclusion": "No",
    "CommercialAutoPublicOrLiveryPassengerConveyanceAndOnDemandDeliveryServicesExclusion": "No",
    "NonOwnedAutoWanted": "Yes",
    "HiredAutoWanted": "Yes",
    "LegalEntity": "Partnership",
    "UninsuredMotoristsCoverageType": "Combined Single Limit",
    "UninsuredMotoristsCoverageSplitLimit": "Not Applicable",
    "UninsuredMotoristsCoverageCombinedSingleLimit": "100,000",
    "UninsuredMotoristsCoverageStacked": "Non-Stacked Coverage",
    "UninsuredMotoristPropertyDamageDeductible": "Full Coverage",
    "UnderinsuredMotoristsCoverageType": "Combined Single Limit",
    "UnderinsuredMotoristsCoverageCombinedSingleLimit": "125,000",
    "UnderinsuredMotoristsCoverageSplitLimit": "Not Applicable",
    "UnderinsuredMotoristsCoveragePulledByPowerUnit": "Yes",
    "UnderinsuredMotoristsCoverageStacked": "Non-Stacked Coverage",
    "EmployeeBenefitsLiabilityCoverageManualpremium": "45",
    "AddlInsGLLessorOfLeasedEqpmtAutomtcStatusWhenRqdInLeasedAgrmtWithYouManualPremium": "478",
    "AddInsGLCoveragesConcessionairesTradingUnderYourNameManualPremium": "8000",
    "TortLimitation": "Named Insured and all Regular Operators accepted Tort Limitation",
    "TortLimitationCode": "C",
    "IstheInsuredaGovernmentalSubdivision": "No",
    "PollutionLiabBroadenedCovBusinessAutoMotorCarrierTruckersCovFormsManualPremium": "100",
    "PollutionLiabilityBroadenedCoverageForCoveredAutosGarageCoverageFormManualPremium": "100",
    "CoverageForInjuryToLeasedWorkersManualPremium": "100",
    "LimitedMexicoCoverageManualPremium": "100",
    "FellowEmployeeCovManualPremium": "100",
    "FellowEmployeeCoverageForDesignatedEmployeesPositionsManualPremium": "100",
    "OptionalLimitsLossOfUseExpensesManualPremium": "100",
    "FungiOrBacteriaExclusionGarageOperationsOtherThanCoveredAutosManualPremium": "100",
    "LimitedFungiOrBacteriaCoverageForGarageOperationsOtherThanCoveredAutosManualPremium": "100",
    "SilicaOrSilicaRelatedDustExclusionForCoveredAutosExposureManualPremium": "100",
    "SilicaOrSilicaRelatedDustExclusionForOtherThanCoveredAutosExposureGarageCoverageFormManualPremium": "100",
    "ExclusionYear2000ComputerRelatedElectronicProblemsProductsWorkManualPremium": "100",
    "ExclusionYear2000ComputerRelatedElectronicProblemsExceptionBodilyInjuryPremisesManualPremium": "100",
    "Year2000ComputerRelatedElectronicProblemsExclusionSpecifiedCoveragesManualPremium": "100",
    "Year2000LimitedCoverageOptionsManualPremium": "100",
    "WorldwideGeneralLiabilityCoveragesManualPremium": "100",
    "ExpandedCoverageTerritoryForGeneralLiabilityCoveragesAdditionalScheduledCountriesManualPremium": "100",
    "LimitedContractualLiabilityCoverageForPersonalAndAdvertisingInjuryManualPremium": "100",
    "DesignatedLocationsGeneralLiabilityAggregateLimitForCertainGeneralLiabilityCoveragesManualPremium": "100",
    "AmendmentOfLimitsOfInsuranceGeneralLiabilityCoveragesManualPremium": "100",
    "ExtendedReportingPeriodEndorsementForEmployeeBenefitsLiabilityCoverageManualPremium": "100",
    "LimitedProductWithdrawalExpenseEndorsementManualPremium": "100",
    "CustomerComplaintLegalDefenseCoverageManualPremium": "100",
    "AbuseOrMolestationExclusionForGeneralLiabilityCoveragesManualPremium": "100",
    "CommunicableDiseaseExclusionForGeneralLiabilityCoveragesManualPremium": "100",
    "ExclusionDesignatedWorkYouPerformedManualPremium": "100",
    "ExclusionDesignatedProductsManualPremium": "100",
    "ExclusionNewlyAcquiredOrFormedAutoDealershipManualPremium": "100",
    "TotalBankruptcyOrInsolvencyExclusionForActsErrorsOrOmissionsLiabilityCoveragesManualPremium": "100",
    "ChangesToTheBankruptcyOrInsolvencyExclusionForActsErrorsOrOmissionsLiabilityCoveragesManualPremium": "100",
    "ConnecticutChangesLiabilityOfMunicipalitiesManualPremium": "100",
    "EmployeeBenefitsLiabilityCoverageWithNoCoverageForNewlyAcquiredOrFormedAutoDealershipManualPremium": "100",
    "ExtendedReportingPeriodForEmpBensLiabilityCoverageWithNoCoverageForNewlyAcqrdOrFormedAutoDealershipManualPremium": "100",
    "CustomerComplaintLegalDefenseCoverageWithNoCoverageForNewlyAcquiredOrFormedAutoDealershipManualPremium": "100",
    "AdditionalInsuredGaragesGrantorFranchiseDetailManualPremium": "100",
    "AdditionalInsuredLessorOfLeasedEquipmentDetailManualPremium": "100",
    "AutosLeasedHiredRentedWithDriversPhysicalDamageCovCollisionCoverageManualPremium": "100",
    "AutosLeasedHiredRentedWithDriversPhysicalDamageCovComprehensiveCoverageManualPremium": "100",
    "AutosLeasedHiredRentedWithDriversPhysicalDamageCovSpecifiedCausesOfLossCoverageManualPremium": "100",
    "AddedPersonalInjuryProtectionDetailAdditionalChiropracticTreatments": "Yes",
    "LCMLiability": "1",
    "LCMPhysicalDamage": "1",
    "RiskAnalyzerWanted": "No",
    "IsCommercialAutoAbuseOrMolestationExclusionForGeneralLiabilityCoveragesNeeded": "Yes",
    "IsCommercialAutoAddlInsuredGenllLiabilityCovsLessorOfLeasedEquipmtAutomtcStatusWhenRqdInLeasedAgrmtWithYouNeeded": "Yes",
    "IsCommercialAutoExclusionDesignatedProductsNeeded": "Yes",
    "IsCommercialAutoExclusionNewlyAcquiredOrFormedAutoDealershipNeeded": "Yes",
    "IsCommercialAutoExclusionDesignatedWorkYouPerformedNeeded": "Yes",
    "IsCommercialAutoCommunicableDiseaseExclusionForGeneralLiabilityCoveragesNeeded": "Yes",
    "IsCommercialAutoWorldwideGeneralLiabilityCoveragesNeeded": "Yes",
    "IsCommercialAutoExpandedCoverageTerritoryForGeneralLiabilityCoveragesAdditionalScheduledCountriesNeeded": "Yes",
    "IsCommercialAutoTotalBankruptcyOrInsolvencyExclusionForActsErrorsOrOmissionsLiabilityCoveragesNeeded": "Yes",
    "IsCommercialAutoCustomerComplaintLegalDefenseCoverageNeeded": "Yes",
    "IsCommercialAutoExclusionOfFederalEmployeesUsingAutosInGovernmentBusinessNeeded": "Yes",
    "IsCommercialAutoAdditionalInsuredGeneralLiabilityCoveragesConcessionairesTradingUnderYourNameNeeded": "Yes",
    "IsCommercialAutoLimitedProductWithdrawalExpenseEndorsementNeeded": "Yes",
    "IsCommercialAutoDesignatedLocationsGeneralLiabilityAggregateLimitForCertainGeneralLiabilityCoveragesNeeded": "Yes",
    "IsCommercialAutoChangesToTheBankruptcyOrInsolvencyExclusionForActsErrorsOrOmissionsLiabilityCoveragesNeeded": "Yes",
    "IsCommercialAutoWestVirginiaChangesCancellationIL0281Needed": "Yes",
    "IsCommercialAutoLimitedFungiOrBacteriaCoverageForGarageOperationsOtherThanCoveredAutosNeeded": "Yes",
    "IsCommercialAutoWashingtonExclusionOfTerrorismInvolvingNuclearBiologicalOrChemicalTerrorismNeeded": "Yes",
    "IsCommercialAutoWashingtonExclusionOfTerrorismNeeded": "Yes",
    "IsCommercialAutoEmployeesUsingAutosInGovernmentBusinessNeeded": "Yes",
    "IsCommercialAutoDealersDriveAwayCollisionCovNeeded": "Yes",
    "IsCommercialAutoNamedDriverCollisionCovPolLvlNeeded": "Yes",
    "Truck": [
      {
        "TruckDetail": {
          "NoOfVehicles": "10",
          "AddressLine1": "8TH",
          "AddressLine2": "BROADWAY",
          "City": "Fire Island",
          "County": "Suffolk County",
          "State": "GA",
          "ZipCode": "30002",
          "VehicleType": "Truck",
          "TruckSizeClass": "Medium Truck",
          "TruckTrailerHowUsed": "Non-trucking Operations",
          "TruckUsedAsTNCOrOnDemand": "Used As Transportation Network Company Only",
          "TruckPercentageOfTransportationNetworkServiceAutoUse": "20% to 49.9%",
          "TruckSafetyScoreDiscountApplies": "Yes",
          "TruckSafetyScore": "31 - 34",
          "TruckBusinessUseClass": "Service",
          "TruckRadiusClass": "Intermediate",
          "TruckFleet": "No",
          "TruckSecondaryClass": "Truckers - Tow Trucks For-Hire",
          "TruckOriginalCostNew": "10000",
          "TruckStatedAmount": "4500",
          "TruckYear": "2012",
          "TruckMake": "CHEVROLET",
          "TruckModel": "SUBURBAN",
          "TruckVIN": "23",
          "TruckStartOfOperations": "12/12/2017",
          "TruckEndOfOperations": "12/12/2018",
          "TruckMedicalPaymentsCoverageLimit": "1,000",
          "TruckLiabilityCoveragePercentOfMilesDrivenInGreenZone": "51 - 60%",
          "TruckLiabilityCoverageType": "Combined Single Limit",
          "TruckLiabilityCoverageLimit": "150,000",
          "TruckLiabilityCoverageDeductible": "250 Combined Single Limit",
          "TruckHiredAutosSpecifiedAsCoveredAutosYouOwn": "Yes",
          "TruckLessorAdditionalInsuredAndLossPayee": "Yes",
          "TruckAutoRentedToOtherMotorCarriers": "Yes",
          "TruckAgriculturalProduceTrailersSeasonal": "No",
          "TruckUninsuredMotoristsCoverageWanted": "Yes",
          "TruckZipCodeOverride": "5656",
          "TruckCollisionCoverageCoverageType": "Stated Amount",
          "TruckCollisionCoveragePercentOfMilesDrivenInGreenZone": "71 - 80%",
          "TruckCollisionCoverageDeductible": "2,000",
          "TruckOtherThanCollisionCoverageCoverageType": "ACV",
          "TruckOtherThanCollisionCoverageDeductible": "1,000",
          "TruckOtherThanCollisionCoveragePercentOfMilesDrivenInGreenZone": "51 - 60%",
          "TruckAccidentPreventionDiscount": "Yes",
          "TruckPIPCoverageCoverageType": "Yes",
          "TruckLiabilityCoverageownedByEmployer": "No",
          "TruckLiabilitymoreThanOneRoundTrip": "Yes",
          "TruckLiabilityCoveragetransportationOfEmployees": "No",
          "TruckLiabilityCoveragefarecharged": "Yes",
          "TruckLiabilityCoveragefarmRegistrationCertificate": "No",
          "TruckLiabilityCoverageLocationUse": "Intrastate",
          "TruckUnderinsuredMotoristsCoverageWanted": "Yes",
          "TruckSugarCaneHaulersPeriodOfCoverage": "75 Days",
          "TruckSugarCaneHaulersCoverage": "Trucks or Tractors with Semi-Trailers",
          "TruckPassengerHazard": "Passenger Hazard Included",
          "TruckCarnivalParade": "Lessee or Hirer's Risks",
          "TruckDefensiveDrivingCourseCredit": "No",
          "TruckMatureDriverImprovementCourseDiscount": "No",
          "TruckJunkDealerClass": "Yes",
          "TruckTotalPairsJunkDealersPlates": "2",
          "TruckTotalSetsOfDealerPlates": "4",
          "AudioVisualAndDataElectronicEquipmentCoverageLimit": "2,500",
          "RentalReimbursementCoverageDailyRentalAmount": "35",
          "RentalReimbursementCoverageMaximumRentalDays": "15",
          "TruckAntiTheftDevice": "Alarm Only",
          "TruckAntiTheftVehicleRecoveryDevice": "Fuel Cutoff",
          "TruckAuxillaryRunningLampsDiscount": "Yes",
          "TruckGaragingLocation": "Fire Island",
          "TruckTelematicsDiscountApplies": "Yes",
          "LCMLiability": "1",
          "LCMPhysicalDamage": "1"
        }
      }
    ],
    "PrivatePassenger": [
      {
        "PrivatePassengerDetail": {
          "NoOfVehicles": "10",
          "AddressLine1": "8TH",
          "AddressLine2": "BROADWAY",
          "City": "Fire Island",
          "County": "Suffolk County",
          "State": "GA",
          "ZipCode": "30003",
          "PrivatePassengerYear": "2017",
          "VehicleType": "Private Passenger",
          "PrivatePassengerType": "Personal Use or Farm Use - Nonfleet Vehicle",
          "PrivatePassengerLiabilityCoveragePercentOfMilesDrivenInGreenZone": "81 - 90%",
          "PrivatePassengerSafetyScoreDiscountApplies": "Yes",
          "PrivatePassengerSafetyScore": "27 - 30",
          "PrivatePassengerOperatorExperience": "No Operator Licensed Less Than 5 Years",
          "PrivatePassengerUse": "To or From Work 15 or More Miles",
          "PrivatePassengerOriginalCostNew": "300",
          "PrivatePassengerStatedAmount": "10000",
          "PrivatePassengerFleet": "No",
          "PrivatePassengerUsedAsTNCOrOnDemand": "Not Used In A Transportation Network Company Or On-Demand Capacity",
          "PrivatePassengerPercentageOfTransportationNetworkServiceAutoUse": "80% or More",
          "PrivatePassengerMake": "KENWORTH",
          "PrivatePassengerModel": "CONSTRUCTION",
          "PrivatePassengerVIN": "1NKDL40X19J239303",
          "PrivatePassengerLiabilityCoverageType": "Combined Single Limit",
          "PrivatePassengerLiabilityCoverageLimit": "100,000",
          "PrivatePassengerLiabilityCoverageDeductible": "50,000 Combined Single Limit",
          "PrivatePassengerMedicalPaymentsCoverageLimit": "2,000",
          "PrivatePassengerHiredAutosSpecifiedAsCoveredAutosYouOwn": "Yes",
          "PrivatePassengerLessorAdditionalInsuredAndLossPayee": "No",
          "PrivatePassengerUninsuredMotoristsCoverageWanted": "Yes",
          "PrivatePassengerZipCodeOverride": "other",
          "PrivatePassengerCollisionCoverageCoverageType": "ACV",
          "PrivatePassengerCollisionCoveragePercentOfMilesDrivenInGreenZone": "91 - 100%",
          "PrivatePassengerCollisionCoverageDeductible": "1,000",
          "PrivatePassengerOtherThanCollisionCoverageCoverageType": "ACV",
          "PrivatePassengerOtherThanCollisionCoverageDeductible": "Full Coverage",
          "PrivatePassengerOtherThanCollisionCoveragePercentOfMilesDrivenInGreenZone": "61 - 70%",
          "PrivatePassengerOtherThanCollisionCoverageFullGlassCoverage": "Yes",
          "PrivatePassengerTowingLaborCoverageLimit": "100",
          "PrivatePassengerAccidentPreventionDiscount": "No",
          "PrivatePassengerPassiveRestraintDiscount": "Yes",
          "PrivatePassengerLiabilityCoverageManualPremium": "15000",
          "PrivatePassengerMedicalPaymentsCoverageManualPremium": "457",
          "PrivatePassengerCollisionCoverageManualPremium": "1500",
          "PrivatePassengerPIPCoverageCoverageType": "Not Applicable",
          "PrivatePassengerTowingLaborCoverageManualPremium": "35",
          "PrivatePassengerUnderinsuredMotoristsCoverageWanted": "Yes",
          "PrivatePassengerUninsuredMotoristsCoverageManualPremium": "458",
          "PrivatePassengerMatureDriverImprovementCourseDiscount": "No",
          "PrivatePassengerAccidentPreventionRefresherDiscount": "No",
          "PrivatePassengerDefensiveDrivingCourseCredit": "No",
          "PrivatePassengerSafetyFeatures": "Not Applicable/Not Installed",
          "PrivatePassengerAntiTheftDevice": "Alarm Only",
          "PrivatePassengerAntiTheftVehicleRecoveryDevice": "Fuel Cutoff",
          "AudioVisualAndDataElectronicEquipmentCoverageLimit": "2,500",
          "RentalReimbursementCoverageDailyRentalAmount": "35",
          "RentalReimbursementCoverageMaximumRentalDays": "15",
          "PrivatePassengerAuxillaryRunningLampsDiscount": "Yes",
          "PrivatePassengerGaragingLocation": "Fire Island",
          "PrivatePassengerTelematicsDiscountApplies": "Yes",
          "PrivatePassengerGrossVehicleWeightOver10000": "No",
          "LCMLiability": "1",
          "LCMPhysicalDamage": "1"
        }
      }
    ],
    "HiredAuto": [
      {
        "HiredAutoDetail": {
          "HiredAutoTotalCostOfHireInsuredPrimary": "2500",
          "HiredAutoTotalCostOfHireOwnerPrimary": "1500",
          "HiredAutoLiabilityCoverageLimit": "500,000",
          "HiredAutoLiabilityCoverageDeductible": "100,000 Combined Single Limit",
          "HiredAutoCollisionCoverageTotalCostOfHire": "1000",
          "HiredAutoCollisionCoverageDeductible": "500",
          "HiredAutoOtherThanCollisionCoverageTotalCostOfHire": "1000",
          "HiredAutoOtherThanCollisionCoverageCoverageType": "Comprehensive",
          "HiredAutoOtherThanCollisionCoverageDeductible": "Full Coverage",
          "HiredAutoTruckersLiabilityCoverageTotalNumberOfVehicles": "1",
          "HiredAutoTruckersLiabilityCoverageTruckersPremium": "550",
          "HiredAutoTruckersLiabilityCoveragePrimaryCostOfHireTruckers": "5",
          "HiredAutoTruckersLiabilityCoverageExcessCostOfHireTruckers": "15000",
          "HiredAutoInsuranceRequired": "Yes",
          "HiredAutoLiabilityCoverageType": "Combined Single Limit",
          "HiredAutoLiabilityCoveragePropertyDamageLimitText": "10,000",
          "HiredAutoPermittedCarrier": "No",
          "LCMLiability": "1",
          "LCMPhysicalDamage": "1"
        }
      }
    ],
    "NonOwnedAuto": [
      {
        "NonOwnedAutoDetail": {
          "NonOwnedAutoNumberOfEmployees": "305",
          "NonOwnedAutoEmployeesAsInsureds": "Yes",
          "NonOwnedAutoSocialServiceAgency": "Yes",
          "NonOwnedAutoNumberOfPartners": "2",
          "NonOwnedAutoNumberOfVolunteers": "15",
          "NonOwnedAutoVolunteersAsInsureds": "Yes",
          "NonOwnedAutoLiabilityCoverageDeductible": "20,000 Combined Single Limit",
          "NonOwnedAutoLiabilityCoverageLimit": "100,000",
          "NonOwnedAutoPropertyDamageLimitText": "10,000",
          "NonOwnedAutoLiabilityCoverageType": "Combined Single Limit",
          "LCMLiability": "1"
        }
      }
    ],
    "CommercialAutoPennsylvaniaNamedIndividualsBroadenedFirstPartyBenefits": [
      {
        "CommercialAutoPennsylvaniaNamedIndividualsBroadenedFirstPartyBenefitsDetail": {
          "MedicalExpenseBenefit": "100,000",
          "AccidentalDeathBenefit": "5,000",
          "CombinationFirstPartyBenefit": "100,000",
          "CoverageType": "Additional First Party Benefit",
          "FuneralExpenseBenefit": "2,500",
          "WorkLossBenefit": "2,500 Monthly / 50,000 Total"
        }
      }
    ]
  },
  "OwnerId": "1",
  "ServiceRequestDetail": {
    "ResponseType": "JSON",
    "OwnerId": "1",
    "UserName": "isorateadmin",
    "Token": "OOGQed0nowd5znplRxd+K4U3E7drUBy87maW7J99IkIDzvGgoByUh/LmDI2IAwfeSPs4c52lfzUdN+4AzB4VJKIlxM43YYOnuAEqinJVQv86XvF1s4ZV+79xE2JEOiQsiL49D56VGmWb8xybOfXY3jYXYhv78BdNPEVeSpD05nyVQfMupKTc+DUDCSDh+Q66NH7byf2vGuvKhu20G4skT8gOkLQ08wT2O7ulrb/RZVxD7KegdQlAOcfta8KLYYE/tyJdLJYDWfyOdKcncNrkaAN24HGs4cVDGV2W2irEbKETK3xYLMzzj7eLEn8pNoypvAZmxQZKOj/iFgsHh8R22QGntLXKQ2+p7qn4MsC8DOgtpys/j2yFF7r7bDZrYi5qfx6cdHvvCJzs/oDvkqsKdmTs0fIgNUW+ky+AOwFa7F+G+DhMPoSG5VfKLDy7K0cDMWzXEgH5Hb/znmhVBpvn9qFfn7Y7Iz3b/lbatQwxXN+n77cIgjwP4/Bu45tZDFPpG/cnLMVAklhzz9xkzXO4GcwmQHeTY61NT2xi+aT5vLZ5AcVPk1y3fNLQ7R1x6fA2xg3qVoraCCi6lo3UnM7eBY9i/8ZeR7r4S1NYOzBpLqOmV6MU4LZBxZ8cU2OeJvBTZQT9EBRbTJ0TDQ7aKONM6KFzS7cAxr3fpE0hTtGwKgWnRKjqXtLc9x6HR26FGFl8mCUe2W2We/oHRRcxno1aVFEDIE1do2qULIoTSAQZlsx78riUsp59Fz2oeouVcyxtqyjaO3jQVWkE9XNgxPhzWtTbnKXG2/vkUFKz1HcybBqiItqTxFbOw5bja1HdDPIp/IoBYU4aoL9gakcKR3ygbJKmM/zdmyy74nYD5tA4I3dHZ2h9KkbatdNU0F4P+MP62+QgCk6JcSbMUVe0T/r3w1a4st9wO1p83ajT0VfEqrXDekvXQ3A3bODxPNcOhvAuB2FxWXDGGRJI6/waqRONm3bvJeDfnQN4Nm3wJnPTDT2q3upzPhTxhit1ts0zaCZ78bVayYZSNdlKQ1UYDJlRW8uQBL2WTjzXX5baQbkqDbKI4p6y72Yb9dzs2eSlp/n7FCraGgRwT5c3Dc6/xu6EhSCiTnb0deP7xM5/Xt+uuvkGJkeASM0QPQRKs+U565zt922s++UkUKEbEAlH/Bji7M8KzScgXdx3Vfb1aKd8L7Z27z4twAuFKpqQOPz25+uJdVrX3EmMjIpUXkNJtWbENLOIkkaF4meaKDxV/M1whMCkRHtjWZ/9FTwXSXH5bvPOMArFEpwntk+UHHusK/VqBh9iJ+vrfO7D+4ZBhPmdtQLgCBIuN/K0RNITTbJfdX96ek4BAa83eNJ+svpTqhT3/kyQgX3cG0DXIPoqDWQFqPG+EcYyibkkmjP+N5N8DwVw/+jtsThx619BfZMQpdSdgXH+yKjJ5zFzLCllaCET/CQMCKXe0g71ngNZEyItCgi2w3yuLklnyxSQTJyC3W9Ep8D1KDcrH409npvvIdV3XQqccfM/F5Ix/k0jJAa2sEfjNSs8Fk1BSBEcemAW0jU9dQrFrGP+JosxjsUGDE9d9aLnAlQMvGlu9hnwvN46Jj0Mo43nbcf/G12bLJKrgV3eRqXwa6uZTe49ccrbo7J7yNofIrD+fevcDDNossGxR5JAdXEVsJBSgT3+kjYKOQPOI/P8BBLE2LBMm48dRuOemmZkolOWTTeEPVVjEJtNwLUYawXN/X/H2qL3ihLSnCIgQk278rBkYFV5w9cXaWtzSVovV2izNKcn9rUCQRzJm2GgyGGAYvJfa8xidf/WxTt8PxOjqC+fvdTtt60t/xiZV4ZiLQnXVQRKUHt9i+6vV0H3YHbzwghKYIRwPrM9LbpvVO8f2HIxhFiVHO7SoF1OLyexije4PUTTpucT7fdZ6zKhZRftdb5dF+U8Pcn2WRsmK/Q5mDcPuySdYqBNfSpCHqQHYXFZcMYZEkjr/BqpE42bt5X9q/YcSSLSWvbJNCK2qg==",
    "BrowserIp": "111.44.20.341",
    "ServiceRequestVersion": "1.0"
  }
}